export const FETCH_CANDIDATES_REQUEST = "FETCH_CANDIDATES_REQUEST";
export const FETCH_CANDIDATES_SUCCESS = "FETCH_CANDIDATES_SUCCESS";
export const FETCH_CANDIDATES_ERROR = "FETCH_CANDIDATES_ERROR";

export const PRELOAD_LIST_REQUEST = "PRELOAD_LIST_REQUEST";
export const PRELOAD_LIST_SUCCESS = "PRELOAD_LIST_SUCCESS";
export const PRELOAD_LIST_ERROR = "PRELOAD_LIST_ERROR";
